### PR TITLE
ELEX-3055: Update all `elexmodel` requirements in an attempt to silence numpy/pandas warnings

### PR DESCRIPTION
**Pull request by dmnapolitano**
## Description

Hello!  The changes in this PR:
* upgrade all required packages to their latest versions;
* silence warnings revealed by our unit tests;
* ensure that all warnings generated in production are being logged (at the `WARN` level) 🎉 

## Jira Ticket

ELEX-3055

## Test Steps

~~Testing this is a bit complicated until [this PR on `elex-solver`](https://github.com/washingtonpost/elex-solver/pull/14) is merged and a new `elex-solver` package exists, but here's what you can do locally:~~

You can now test using `tox` and/or various `elexmodel` commands etc. 😄 🎉

### CODE REVIEW

**Comment by lennybronner** [comment]
The unit and integration tests are currently failing

**Comment by dmnapolitano** [comment]
> The unit and integration tests are currently failing. It looks to me as if elex-solver isn't being installed anymore 🤔

I know, the versions of the packages being used here are too new for the current `elex-solver` package.  So we need a new `elex-solver` package so that these tests will pass 😞

**Comment by lennybronner** [comment]
> > The unit and integration tests are currently failing. It looks to me as if elex-solver isn't being installed anymore 🤔
> 
> I know, the versions of the packages being used here are too new for the current `elex-solver` package. So we need a new `elex-solver` package so that these tests will pass 😞

hmm I'm not sure I understand? Also fwiw, I am getting the same error locally 😞

**Comment by dmnapolitano** [comment]
> > > The unit and integration tests are currently failing. It looks to me as if elex-solver isn't being installed anymore 🤔
> > 
> > 
> > I know, the versions of the packages being used here are too new for the current `elex-solver` package. So we need a new `elex-solver` package so that these tests will pass 😞
> 
> hmm I'm not sure I understand? Also fwiw, I am getting the same error locally 😞

Hmmmm, if you're having trouble running stuff locally, maybe we can look at this together because it's possible my instructions are bad 😞 

But for the unit tests being run here on GitHub, maybe there's a way to do it but I'm not sure it's worth the trouble.  If `elex-live-model` does `pip install elex-solver`, it will wind up with dependency conflicts because the dependencies in `elex-live-model` are now newer than those in the current `elex-solver` 2.0.0 package available on PyPI.  Locally, unless you make sure you're installing your local copy of `elex-solver`, you'll have the same issue 😞

**Comment by dmnapolitano** [comment]
Ok @lennybronner you can now test this branch like you normally would 🎉  Thanks and sorry 😅

**Review by lennybronner — APPROVED** [review]

**Pull request merged**
