### PR TITLE
Elex 2376 add regularization

### PR DESCRIPTION
**Pull request by lennybronner**
## Description
Added a `lambda_` parameter to the CLI and to the client that allows us to specify regularization for our quantile regression model. This will hopefully let us fix situations in which our model is overfit because of fixed effects.

Also added a variable to explicitly set the intercept. This is done for both the `Featurizer` when we add the intercept and for the solver, to avoid regularizing the intercept coefficient.

## Jira Ticket
https://arcpublishing.atlassian.net/browse/ELEX-2376

## Test Steps
Make sure you have elex-solver v1.1.0 installed:
```
pip install elex-solver --upgrade
```

`tox`

First run a model with no features and no fixed effects:
```
elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric --percent_reporting=5 --aggregates=postal_code
```

Then run a model with fixed effects but no regularization:
```
 elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code
```

Then run a model fixed effects and very high regularization:
```
 elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code --lambda=1e4
```

You should notice that the output of the last run (with lambda) will be a lot more similar to the run with no fixed effects than with fixed effects because we are regularizing the fixed effect coefficients to zero.

### CODE REVIEW

**Comment by daragold** [comment]
> ## Description
> Added a `lambda_` parameter to the CLI and to the client that allows us to specify regularization for our quantile regression model. This will hopefully let us fix situations in which our model is overfit because of fixed effects.
> 
> Also added a variable to explicitly set the intercept. This is done for both the `Featurizer` when we add the intercept and for the solver, to avoid regularizing the intercept coefficient.
> 
> ## Jira Ticket
> https://arcpublishing.atlassian.net/browse/ELEX-2376
> 
> ## Test Steps
> Make sure you have elex-solver v1.1.0 installed:
> 
> ```
> pip install elex-solver --upgrade
> ```
> 
> `tox`
> 
> First run a model with no features and no fixed effects:
> 
> ```
> elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric --percent_reporting=5 --aggregates=postal_code
> ```
> 
> Then run a model with fixed effects but no regularization:
> 
> ```
>  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code
> ```
> 
> Then run a model fixed effects and very high regularization:
> 
> ```
>  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code --lambda=1e4
> ```
> 
> You should notice that the output of the last run (with lambda) will be a lot more similar to the run with no fixed effects than with fixed effects because we are regularizing the fixed effect coefficients to zero.

**Comment by daragold** [comment]
> ## Description
> Added a `lambda_` parameter to the CLI and to the client that allows us to specify regularization for our quantile regression model. This will hopefully let us fix situations in which our model is overfit because of fixed effects.
> 
> Also added a variable to explicitly set the intercept. This is done for both the `Featurizer` when we add the intercept and for the solver, to avoid regularizing the intercept coefficient.
> 
> ## Jira Ticket
> https://arcpublishing.atlassian.net/browse/ELEX-2376
> 
> ## Test Steps
> Make sure you have elex-solver v1.1.0 installed:
> 
> ```
> pip install elex-solver --upgrade
> ```
> 
> `tox`
> 
> First run a model with no features and no fixed effects:
> 
> ```
> elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric --percent_reporting=5 --aggregates=postal_code
> ```
> 
> Then run a model with fixed effects but no regularization:
> 
> ```
>  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code
> ```
> 
> Then run a model fixed effects and very high regularization:
> 
> ```
>  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code --lambda=1e4
> ```
> 
> You should notice that the output of the last run (with lambda) will be a lot more similar to the run with no fixed effects than with fixed effects because we are regularizing the fixed effect coefficients to zero.

**Comment by daragold** [comment]
> ## Description
> Added a `lambda_` parameter to the CLI and to the client that allows us to specify regularization for our quantile regression model. This will hopefully let us fix situations in which our model is overfit because of fixed effects.
> 
> Also added a variable to explicitly set the intercept. This is done for both the `Featurizer` when we add the intercept and for the solver, to avoid regularizing the intercept coefficient.
> 
> ## Jira Ticket
> https://arcpublishing.atlassian.net/browse/ELEX-2376
> 
> ## Test Steps
> Make sure you have elex-solver v1.1.0 installed:
> 
> ```
> pip install elex-solver --upgrade
> ```
> 
> `tox`
> 
> First run a model with no features and no fixed effects:
> 
> ```
> elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric --percent_reporting=5 --aggregates=postal_code
> ```
> 
> Then run a model with fixed effects but no regularization:
> 
> ```
>  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code
> ```
> 
> Then run a model fixed effects and very high regularization:
> 
> ```
>  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code --lambda=1e4
> ```
> 
> You should notice that the output of the last run (with lambda) will be a lot more similar to the run with no fixed effects than with fixed effects because we are regularizing the fixed effect coefficients to zero.

This looks good to me. A couple of minor points of clarification: Fixed effects are one way to see the result of adding a big lambda v. having no fixed effects at all. But this isn't specific to fixed effects, yea? This applies to any features.

And I don't think you need to change here, but the commands you have in the test steps would now need Jen's updated fixed-effects input formats.

**Comment by lennybronner** [comment]
> > ## Description
> > Added a `lambda_` parameter to the CLI and to the client that allows us to specify regularization for our quantile regression model. This will hopefully let us fix situations in which our model is overfit because of fixed effects.
> > Also added a variable to explicitly set the intercept. This is done for both the `Featurizer` when we add the intercept and for the solver, to avoid regularizing the intercept coefficient.
> > ## Jira Ticket
> > https://arcpublishing.atlassian.net/browse/ELEX-2376
> > ## Test Steps
> > Make sure you have elex-solver v1.1.0 installed:
> > ```
> > pip install elex-solver --upgrade
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `tox`
> > First run a model with no features and no fixed effects:
> > ```
> > elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric --percent_reporting=5 --aggregates=postal_code
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then run a model with fixed effects but no regularization:
> > ```
> >  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then run a model fixed effects and very high regularization:
> > ```
> >  elexmodel 2020-11-03_USA_G --office_id=P --estimands=turnout --geographic_unit_type=county --pi_method=nonparametric  --percent_reporting=5 --aggregates=postal_code --fixed_effects=postal_code --lambda=1e4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should notice that the output of the last run (with lambda) will be a lot more similar to the run with no fixed effects than with fixed effects because we are regularizing the fixed effect coefficients to zero.
> 
> This looks good to me. A couple of minor points of clarification: Fixed effects are one way to see the result of adding a big lambda v. having no fixed effects at all. But this isn't specific to fixed effects, yea? This applies to any features.
> 
> And I don't think you need to change here, but the commands you have in the test steps would now need Jen's updated fixed-effects input formats.

yes, that is right! It's easiest to see this with fixed effects, but it should also regularize other coefficients close to zero (that being said, I implemented L2 reg and not L1, so they will never get super duper close to zero -- unless they really are not that helpful or the reg number is truly humungous).

Jen allowed for us to use the old input method too, so that should still work

**Review by daragold — APPROVED** [review]

**Pull request merged**
